### ISSUE TITLE
Install Error V3.2

### ISSUE THREAD

**Issue by rugabunda** [BeTheRobotSD/sdxl-comfyui-ultimate-workflow#1]
`) was unexpected at this time.` This is all I am seeing.

I was getting a certificate revocation error before that,  further into the install, after it was trying to `Downloading gfpgan-1.3.8-py3-none-any.whl (52 kB)`

I had to modify your bat file or I would get the following error

`curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.
) was unexpected at this time.`

Adding the line `--ssl-no-revoke` to your curl commands worked, and the install proceeded further... however it still ends with `) was unexpected at this time.` Not sure if the install completed successfully.

Does not `ECHO All custom node dependencies have been updated and/or installed.`

**Comment by rugabunda** [comment]
turning on echo i see the following

```
ComfyUI_windows_portable\ComfyUI\models\insightface>if not exist detection_Resnet50_Final.pth (curl -L --ssl-no-revoke  https://github.com/xinntao/facexlib/releases/download/v0.1.0/detection_Resnet50_Final.pth --output detection_Resnet50_Final.pth )
) was unexpected at this time.
```

**Comment by rugabunda** [comment]
Also getting the following error upon loading comfyui now

```
[comfy_mtb] | INFO -> Some nodes failed to load:
        Failed to import module image_interpolation because ModuleNotFoundError: No module named 'frame_interpolation.eval'
```

**Comment by BeTheRobotSD** [comment]
@rugabunda Please test the latest updater as it may have fixed your issue. The `image_interpolation` module error shouldn't cause any issues with the workflow and I get the same error as well.

**Comment by rugabunda** [comment]
Everything installed flawlessly with the new version, zero errors, no modifications necessary. Great work! thank you for your efforts!

**Comment by rugabunda** [comment]
PS. Have you considered adding a git pull or similar to your own batch file to keep it upto date prior to installing as well? that would be handy
